Repository ImpladeDeveloped/Implactor, pull requests merged in 2018-08, with the labels that each got.

#3 Added a new config language.
  .travis.yml
  README.md
  iconPlugin.png
  resources/iConfig.yml
  resources/languages/English.yml
  resources/languages/Malay.yml
  resources/messages.yml
  src/Implactor/Implade.php
  src/Implactor/listeners/AntiAdvertising.php
  src/Implactor/listeners/AntiCaps.php
  src/Implactor/listeners/AntiSwearing.php
  src/Implactor/listeners/BotListener.php
  src/Implactor/tasks/ClearLaggTask.php
Labels: NEW FEATURES, TO-DO

#5 Spanish support
  resources/iConfig.yml
  resources/languages/Espanish.yml
Labels: APPROVED, NEW FEATURES, TO-DO

#9 Fix all syntax errors and translate on russian language.
  resources/iConfig.yml
  resources/languages/English.yml
  resources/languages/Russian.yml
  src/Implactor/Implade.php
  src/Implactor/entities/BotHuman.php
  src/Implactor/entities/SoccerMagma.php
  src/Implactor/listeners/AntiAdvertising.php
  src/Implactor/listeners/AntiCaps.php
  src/Implactor/listeners/AntiSwearing.php
  src/Implactor/listeners/BotListener.php
  src/Implactor/particles/BotParticles.php
  src/Implactor/particles/DeathParticles.php
  src/Implactor/particles/DespawnParticles.php
  src/Implactor/particles/SpawnParticles.php
  src/Implactor/tasks/BotJumpTask.php
  src/Implactor/tasks/BotSneakTask.php
  src/Implactor/tasks/BotTask.php
  src/Implactor/tasks/BotUnsneakTask.php
  src/Implactor/tasks/BotWalkingTask.php
  src/Implactor/tasks/ChatCooldownTask.php
  src/Implactor/tasks/ClearLaggTask.php
  src/Implactor/tasks/DeathHumanDespawnTask.php
  src/Implactor/tasks/GuardianJoinTask.php
  src/Implactor/tasks/RainbowArmorTask.php
  src/Implactor/tasks/TotemRespawnTask.php
  src/Implactor/tridents/ThrownTrident.php
  src/Implactor/tridents/Trident.php
  src/Implactor/tridents/TridentEntityManager.php
  src/Implactor/tridents/TridentItemManager.php
Labels: APPROVED, NEW FEATURES

#13 Changed every codes.
  src/Implactor/Implade.php
  src/Implactor/listeners/AntiAdvertising.php
  src/Implactor/listeners/AntiCaps.php
  src/Implactor/listeners/AntiSwearing.php
  src/Implactor/tasks/ChatCooldownTask.php
  src/Implactor/tridents/ThrownTrident.php
  src/Implactor/tridents/Trident.php
Labels: AUTHORIZED, BUG, ERROR

#14 Added Head feature to Implactor.
  plugin.yml
  resources/iConfig.yml
  resources/languages/English.yml
  resources/languages/Russian.yml
  src/Implactor/Implade.php
Labels: APPROVED, AUTHORIZED, NEW FEATURES, TO-DO
